import './globals.css'
import { Cairo } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';

const cairo = Cairo({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className={cairo.className}>
        <nav>
          <div style={{width : '100%', height : '80px', backgroundColor : '#000'}}></div>
        </nav>
        <main>
        {children}
        </main>
      </body>
    </html>
  )
}
